package com.example.weatherapp.model

data class WeatherData(
    val temperature: Double,
    val conditions: String,
    val humidity: Int,
    val windSpeed: Double,
    val feelsLike: Double,
    val uvIndex: Int,
    val pressure: Double,
    val visibility: Double,
    val cloudCover: Int,
    val datetime: String,
    val location: String,
    val weatherCode: Int = 0,
    val weatherDescription: String = conditions,
    val minTemperature: Double = temperature * 0.8,
    val maxTemperature: Double = temperature * 1.2,
    val timestamp: Long = System.currentTimeMillis(),
    val description: String = "",
    val snow: Int = 0,
    val precipProbability: Int = 0,
    val precipType: String = "",
    val sunrise: String = "",
    val sunset: String = "",
    val dewPoint: Double = 0.0,
    val precipAmount: Double = 0.0,
    val precipCover: Int = 0,
    val snowDepth: Double = 0.0,
    val windGust: Double = 0.0,
    val windDirection: Int = 0,
    val feelsLikeMax: Double = 0.0,
    val feelsLikeMin: Double = 0.0,
    val solarRadiation: Double = 0.0,
    val solarEnergy: Double = 0.0,
    val severeRisk: Int = 0,
    val moonPhase: Double = 0.0,
    val icon: String = "",
    val stations: String = "",
    val source: String = ""
) {
    companion object {
        fun empty() = WeatherData(
            temperature = 0.0,
            conditions = "",
            humidity = 0,
            windSpeed = 0.0,
            feelsLike = 0.0,
            uvIndex = 0,
            pressure = 0.0,
            visibility = 0.0,
            cloudCover = 0,
            datetime = "",
            location = "",
            weatherCode = 0,
            weatherDescription = "",
            minTemperature = 0.0,
            maxTemperature = 0.0,
            timestamp = 0,
            description = "",
            snow = 0,
            precipProbability = 0,
            precipType = "",
            sunrise = "",
            sunset = "",
            dewPoint = 0.0,
            precipAmount = 0.0,
            precipCover = 0,
            snowDepth = 0.0,
            windGust = 0.0,
            windDirection = 0,
            feelsLikeMax = 0.0,
            feelsLikeMin = 0.0,
            solarRadiation = 0.0,
            solarEnergy = 0.0,
            severeRisk = 0,
            moonPhase = 0.0,
            icon = "",
            stations = "",
            source = ""
        )
    }
} 